### ISSUE TITLE
Rich Text CkEditor Context

### ISSUE THREAD

**Issue by moonraking** [sonata-project/SonataFormatterBundle#103]
I am not sure if this is a Formatter bug or a Sonata-Sandbox bug.

Anyhow, the default context is not being set, the ckeditor_context stays null.
The only way i can figure out of changing the ckeditor_context is to edit the  SonataFormatterBundle/Form/Type/FormatterType.php:175, obviously not ideal!

As I said this might be because the SandBox is not setting this correctly(if not how do I?) or maybe the Formatter bundle is not using ivory_ck_editor->default_config (maybe ts not meant to).

Sorry for the not so concise report...

**Comment by mgrundkoetter** [comment]
I can confirm this. When you use SonataPageBundle and a "Rich Text" block somewhere in the compose mode, the context is null, thus not configurable. I can also confirm that the "fix" mentioned here does solve this issue. So +1 for reading the ivory_ck_editor.default_config setting value instead in this class.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen if this error still exists.
