### ISSUE TITLE
Default formatter 

### ISSUE THREAD

**Issue by tophsic** [sonata-project/SonataFormatterBundle#112]
As I said in my comment on commit 9a7057e55262bf72fc1bc8e231e955b160eb95b6, I do not see anything in the documentation of what we have to write in `default_formatter` configuration.

Thanks for your reactivity :wink:

**Comment by tophsic** [comment]
See my last [comment](https://github.com/sonata-project/SonataFormatterBundle/commit/9a7057e55262bf72fc1bc8e231e955b160eb95b6#commitcomment-13608751) on the discussion.

I missed `sonata_formatters` configuration.

**Comment by OskarStark** [comment]
:+1: Thank you!
