### ISSUE TITLE
Website https://sonata-project.org seems down

### ISSUE THREAD

**Issue by dmidz** [sonata-project/SonataFormatterBundle#117]
Website https://sonata-project.org seems down since many hours.

**Comment by dmidz** [comment]
Seems only a problem with chrome which throws a "ERR_SSL_VERSION_OR_CIPHER_MISMATCH", never get this error before. Firefox is ok.

**Comment by rande** [comment]
We migrate to a new server, and there is cloudflare on front of sonata website. Looks ok from here and on remote servers.
