### ISSUE TITLE
Twig Warning: Illegal offset type

### ISSUE THREAD

**Issue by Tibase** [sonata-project/SonataFormatterBundle#119]
Hello,

From the commit https://github.com/sonata-project/SonataFormatterBundle/commit/3c5c083202b2ff485890d9659ff8708b2276ded2 , Il have : An exception has been thrown during the compilation of a template ("Warning: Illegal offset type") in sandbox 2.4

**Comment by Soullivaneuh** [comment]
Please provide your dependencies versions and the stack trace.

**Comment by Tibase** [comment]
behat/behat                                      v2.5.5              Scenario-oriented BDD framework for PHP 5.3
behat/common-contexts                            dev-master 570fb7b  Commonly used contexts for Behat
behat/gherkin                                    v2.3.5              Gherkin DSL parser for PHP 5.3
behat/mink                                       v1.7.0              Browser controller/emulator abstraction for PHP
behat/mink-browserkit-driver                     v1.3.0              Symfony2 BrowserKit driver for Mink framework
behat/mink-extension                             v1.3.3              Mink extension for Behat
behat/mink-goutte-driver                         v1.2.0              Goutte driver for Mink framework
behat/mink-selenium2-driver                      v1.3.0              Selenium2 (WebDriver) driver for Mink framework
behat/transliterator                             v1.1.0              String transliterator
cocur/slugify                                    v1.4                Converts a string into a slug.
dflydev/markdown                                 v1.0.3              PHP Markdown & Extra
doctrine/annotations                             v1.2.7              Docblock Annotations Parser
doctrine/cache                                   v1.4.2              Caching library offering an object-oriented API for many cach...
doctrine/collections                             v1.3.0              Collections Abstraction library
doctrine/common                                  v2.5.1              Common Library for Doctrine projects
doctrine/data-fixtures                           dev-master a02f0e7  Data Fixtures for all Doctrine Object Managers
doctrine/dbal                                    v2.4.4              Database Abstraction Layer
doctrine/doctrine-bundle                         v1.5.2              Symfony DoctrineBundle
doctrine/doctrine-cache-bundle                   v1.0.1              Symfony2 Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle                v2.2.1              Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle              dev-master 93ec729  Symfony DoctrineMigrationsBundle
doctrine/inflector                               v1.0.1              Common String Manipulations with regard to casing and singula...
doctrine/instantiator                            1.0.5               A small, lightweight utility to instantiate objects in PHP wi...
doctrine/lexer                                   v1.0.1              Base library for a lexer that can be used in Top-Down, Recurs...
doctrine/migrations                              dev-master d196ddc  Database Schema migrations using Doctrine DBAL
doctrine/orm                                     v2.4.8              Object-Relational-Mapper for PHP
egeloen/ckeditor-bundle                          2.5.2               Provides a CKEditor integration for your Symfony2 Project.
egeloen/json-builder                             1.0.3               JSON builder with escaping control for PHP 5.3+
endroid/qrcode                                   1.5.4               Endroid QR Code
endroid/qrcode-bundle                            1.5.1               Endroid Qr Code Bundle for Symfony
fabpot/goutte                                    v1.0.7              A simple PHP Web Scraper
fr3d/ldap-bundle                                 2.0.x-dev 59d002d   This package provide users and authentication services based ...
friendsofsymfony/comment-bundle                  dev-master 5e42c74  This Bundle provides threaded comment functionality for Symfo...
friendsofsymfony/rest-bundle                     1.7.1               This Bundle provides various tools to rapidly develop RESTful...
friendsofsymfony/user-bundle                     v1.3.6              Symfony FOSUserBundle
fzaninotto/faker                                 v1.5.0              Faker is a PHP library that generates fake data for you.
gedmo/doctrine-extensions                        v2.4.7              Doctrine2 behavioral extensions
guzzle/guzzle                                    v3.9.3              PHP HTTP client. This library is deprecated in favor of https...
imagine/imagine                                  v0.6.3              Image processing for PHP 5.3
incenteev/composer-parameter-handler             v2.1.1              Composer script handling your ignored parameter file
instaclick/php-webdriver                         1.4.3               PHP WebDriver for Selenium 2
jdorn/sql-formatter                              v1.2.17             a PHP SQL highlighting library
jms/metadata                                     1.5.1               Class/method/property metadata management in PHP
jms/parser-lib                                   1.0.0               A library for easily creating recursive-descent parsers.
jms/serializer                                   0.16.0              Library for (de-)serializing data of any complexity; supports...
jms/serializer-bundle                            0.13.0              Allows you to easily serialize, and deserialize data of any c...
knplabs/gaufrette                                v0.1.9              PHP5 library that provides a filesystem abstraction layer
knplabs/knp-components                           1.3.2               Knplabs component library
knplabs/knp-markdown-bundle                      1.3.2               Knplabs markdown bundle transforms markdown into html
knplabs/knp-menu                                 v2.1.0              An object oriented menu library
knplabs/knp-menu-bundle                          v2.1.0              This bundle provides an integration of the KnpMenu library
knplabs/knp-paginator-bundle                     2.5.0               Paginator bundle for Symfony2 to automate pagination and simp...
knplabs/knp-snappy                               0.4.2               PHP5 library allowing thumbnail, snapshot or PDF generation f...
knplabs/knp-snappy-bundle                        dev-master 2aa510c  Easily create PDF and images in Symfony2 by converting Twig/H...
kriswallsmith/assetic                            v1.3.0              Asset Management for PHP
kriswallsmith/buzz                               v0.15               Lightweight HTTP client
liuggio/ExcelBundle                              v2.0.2              This is a Symfony2 Bundle helps you to read and write Excel f...
matthiasnoback/symfony-config-test               v0.4.0              Library for testing user classes related to the Symfony Confi...
matthiasnoback/symfony-dependency-injection-test v0.7.4              Library for testing user classes related to the Symfony Depen...
michelf/php-markdown                             1.4.0               PHP Markdown
monolog/monolog                                  1.17.1              Sends your logs to files, sockets, inboxes, databases and var...
mopa/bootstrap-bundle                            v3.0.0-beta3        Easy integration of twitters bootstrap into symfony2
mopa/composer-bridge                             v1.5.0              Symfony2 Composer Bridge
nelmio/api-doc-bundle                            2.9.0               Generates documentation for your REST API from annotations
phpcollection/phpcollection                      0.4.0               General-Purpose Collection Library for PHP
phpdocumentor/reflection-docblock                2.0.4               
phpoffice/phpexcel                               1.8.1               PHPExcel - OpenXML - Read, Create and Write Spreadsheet docum...
phpoption/phpoption                              1.5.0               Option Type for PHP
phpspec/prophecy                                 v1.5.0              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                        2.2.4               Library that provides collection, processing, and rendering f...
phpunit/php-file-iterator                        1.4.1               FilterIterator implementation that filters files based on a l...
phpunit/php-text-template                        1.2.1               Simple template engine.
phpunit/php-timer                                1.0.7               Utility class for timing
phpunit/php-token-stream                         1.4.8               Wrapper around PHP's tokenizer extension.
phpunit/phpunit                                  4.8.11              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects                     2.3.8               Mock Object library for PHPUnit
psr/log                                          1.0.0               Common interface for logging libraries
sebastian/comparator                             1.2.0               Provides the functionality to compare PHP values for equality
sebastian/diff                                   1.3.0               Diff implementation
sebastian/environment                            1.3.2               Provides functionality to handle HHVM/PHP environments
sebastian/exporter                               1.2.1               Provides the functionality to export PHP variables for visual...
sebastian/global-state                           1.1.0               Snapshotting of global state
sebastian/recursion-context                      1.0.1               Provides functionality to recursively process PHP variables
sebastian/version                                1.0.6               Library that helps with managing the version number of Git-ho...
sensio/distribution-bundle                       v2.3.22             The base bundle for the Symfony Distributions
sensio/framework-extra-bundle                    v2.3.4              This bundle provides a way to configure your controllers with...
sensio/generator-bundle                          v2.5.3              This bundle generates code for you
simplethings/entity-audit-bundle                 v0.7                Audit for Doctrine Entities
sonata-project/admin-bundle                      dev-master ff2375d  Symfony SonataAdminBundle
sonata-project/block-bundle                      dev-master 52211e2  Symfony SonataBlockBundle
sonata-project/cache                             dev-master f2f6be9  Cache library
sonata-project/cache-bundle                      dev-master eb6bd6d  This bundle provides caching services
sonata-project/classification-bundle             dev-master 3c9c46e  Symfony SonataClassificationBundle
sonata-project/comment-bundle                    dev-master 5ba373a  Symfony SonataCommentBundle
sonata-project/core-bundle                       dev-master c5cb064  Symfony SonataCoreBundle
sonata-project/datagrid-bundle                   dev-master cc42f28  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions               1.0.2               Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle         dev-master 02b1205  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminB...
sonata-project/easy-extends-bundle               dev-master 3ca362f  Symfony SonataEasyExtendsBundle
sonata-project/ecommerce                         dev-develop 7d8471f E-Commerce solution provided by Sonata
sonata-project/exporter                          dev-master 92835b5  Lightweight Exporter library
sonata-project/formatter-bundle                  dev-master 079b57c  Symfony SonataFormatterBundle
sonata-project/google-authenticator              1.0.2               Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle                       dev-master 49be46e  Symfony SonataIntlBundle
sonata-project/media-bundle                      dev-master 60f7191  Symfony SonataMediaBundle
sonata-project/news-bundle                       dev-master 0ec37b4  Symfony SonataNewsBundle
sonata-project/notification-bundle               dev-master 904979e  Symfony SonataNotificationBundle
sonata-project/page-bundle                       dev-master 82bc16a  Symfony SonataPageBundle
sonata-project/seo-bundle                        2.0.0               Symfony SonataSeoBundle
sonata-project/sonata-composer                   dev-master 6ebe1f3  
sonata-project/timeline-bundle                   dev-master 50bde51  Symfony SonataTimelineBundle ~ integrate SpyTimelineBundle in...
sonata-project/user-bundle                       dev-master 4ce8c13  Symfony SonataUserBundle
stephpy/timeline                                 v1.0.4              Standalone library to create timelines
stephpy/timeline-bundle                          2.2.0               Symfony2 bundle to make timeline
stof/doctrine-extensions-bundle                  v1.2.1              Integration of the gedmo/doctrine-extensions with Symfony2
swiftmailer/swiftmailer                          v5.4.1              Swiftmailer, free feature-rich PHP mailer
symfony-cmf/routing                              1.3.0               Extends the Symfony2 routing component for dynamic routes and...
symfony-cmf/routing-bundle                       1.3.5               Symfony RoutingBundle
symfony/assetic-bundle                           v2.7.0              Integrates Assetic into Symfony2
symfony/monolog-bundle                           2.8.1               Symfony MonologBundle
symfony/phpunit-bridge                           2.7.x-dev 896bbd1   Symfony PHPUnit Bridge
symfony/swiftmailer-bundle                       v2.3.8              Symfony SwiftmailerBundle
symfony/symfony                                  v2.7.5              The Symfony PHP framework
twbs/bootstrap                                   v3.0.0              Sleek, intuitive, and powerful mobile first front-end framewo...
twig/extensions                                  v1.3.0              Common additional features for Twig that do not directly belo...
twig/twig                                        v1.22.2             Twig, the flexible, fast, and secure template language for PHP
willdurand/faker-bundle                          1.2.1               Put the awesome Faker lib into the DIC and populate your data...
willdurand/jsonp-callback-validator              v1.1.0              JSONP callback validator.
willdurand/negotiation                           1.5.0               Content Negotiation tools for PHP provided as a standalone li...
zendframework/zend-ldap                          2.5.1               provides support for LDAP operations including but not limite...
zendframework/zend-stdlib                        2.5.1

**Comment by Tibase** [comment]
error with "sonata-project/formatter-bundle": "~2.4@dev",

**Comment by Tibase** [comment]
stack trace 

[1] Twig_Error_Syntax: An exception has been thrown during the compilation of a template ("Warning: Illegal offset type") in "AppBundle::avc_www_layout.html.twig".
    at n/a
        in /var/www/intrinfo/app/cache/dev/classes.php line 3767

    at Twig_Environment->compileSource('{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}
{% extends 'SonataPageBundle::base_layout.html.twig' %}

{% block sonata_page_container %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1" id="superglobal">

                

                <div class="row">
                    <div class="col-md-12">
                        {{ sonata_page_render_container('header', 'global') }}
                    </div>
                </div>



                {% block sonata_page_breadcrumb %}
                    <div class="row">
                        <div class="col-md-12">
                            {% if sonata_seo_context is not defined %}
                                {% set sonata_seo_context = 'homepage' %}
                            {% endif %}
                        </div>
                    </div>
                {% endblock %}

                <div class="row">
                    <div class="col-md-12">
                        {% block page_content %}
                            {% if content is defined %}
                                {{ content|raw }}
                            {% else %}
                                {% set content = block('content') %}
                                {% if content|length > 0 %}
                                    {{ content|raw }}
                                {% elseif page is defined %}
                                    {{ sonata_page_render_container('content', page) }}
                                {% endif %}
                            {% endif %}
                        {% endblock %}
                    </div>
                </div>


                <footer class="row">
                    {{ sonata_page_render_container('footer', 'global') }}
                </footer>

            </div>
        </div>
    </div>
{% endblock %}
', 'AppBundle::avc_www_layout.html.twig')
        in /var/www/intrinfo/app/cache/dev/classes.php line 3634

    at Twig_Environment->loadTemplate('AppBundle::avc_www_layout.html.twig')
        in /var/www/intrinfo/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php line 126

    at Symfony\Bridge\Twig\TwigEngine->load('AppBundle::avc_www_layout.html.twig')
        in /var/www/intrinfo/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php line 50

    at Symfony\Bridge\Twig\TwigEngine->render('AppBundle::avc_www_layout.html.twig', array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(Page), 'site' => object(Site)))
        in /var/www/intrinfo/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php line 72

    at Symfony\Bundle\TwigBundle\TwigEngine->render('AppBundle::avc_www_layout.html.twig', array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(Page), 'site' => object(Site)))
        in /var/www/intrinfo/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php line 97

    at Symfony\Bundle\TwigBundle\TwigEngine->renderResponse('AppBundle::avc_www_layout.html.twig', array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(Page), 'site' => object(Site)), object(Response))
        in /var/www/intrinfo/app/cache/dev/classes.php line 12310

    at Sonata\PageBundle\Page\TemplateManager->renderResponse('avcwww', array('page' => object(Page), 'site' => object(Site)), object(Response))
        in /var/www/intrinfo/app/cache/dev/classes.php line 12223

    at Sonata\PageBundle\Page\Service\DefaultPageService->execute(object(Page), object(Request), array('page' => object(Page), 'site' => object(Site)), object(Response))
        in /var/www/intrinfo/app/cache/dev/classes.php line 12162

    at Sonata\PageBundle\Page\PageServiceManager->execute(object(Page), object(Request), array(), null)
        in  line 

    at call_user_func_array(array(object(PageServiceManager), 'execute'), array(object(Page), object(Request), array(), null))
        in /var/www/intrinfo/app/bootstrap.php.cache line 3109

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /var/www/intrinfo/app/bootstrap.php.cache line 3071

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /var/www/intrinfo/app/bootstrap.php.cache line 3222

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Request), '1', true)
        in /var/www/intrinfo/app/bootstrap.php.cache line 2444

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /var/www/intrinfo/web/app_dev.php line 25

[2] Symfony\Component\Debug\Exception\ContextErrorException: Warning: Illegal offset type
    at n/a
        in /var/www/intrinfo/app/cache/dev/classes.php line 4107

    at Symfony\Component\Debug\ErrorHandler->handleError('2', 'Illegal offset type', '/var/www/intrinfo/app/cache/dev/classes.php', '4107', array('extension' => object(TextFormatterExtension), 'name' => object(TextFormatterExtension), 'filter' => object(Twig_SimpleFilter)))
        in /var/www/intrinfo/app/cache/dev/classes.php line 4107

    at Twig_Environment->initExtension(object(TextFormatterExtension))
        in /var/www/intrinfo/app/cache/dev/classes.php line 4095

    at Twig_Environment->initExtensions()
        in /var/www/intrinfo/app/cache/dev/classes.php line 4045

    at Twig_Environment->getUnaryOperators()
        in /var/www/intrinfo/vendor/twig/twig/lib/Twig/Lexer.php line 371

    at Twig_Lexer->getOperatorRegex()
        in /var/www/intrinfo/vendor/twig/twig/lib/Twig/Lexer.php line 65

    at Twig_Lexer->__construct(object(Twig_Environment))
        in /var/www/intrinfo/app/cache/dev/classes.php line 3713

    at Twig_Environment->getLexer()
        in /var/www/intrinfo/app/cache/dev/classes.php line 3723

    at Twig_Environment->tokenize('{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}
{% extends 'SonataPageBundle::base_layout.html.twig' %}

{% block sonata_page_container %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1" id="superglobal">

                

                <div class="row">
                    <div class="col-md-12">
                        {{ sonata_page_render_container('header', 'global') }}
                    </div>
                </div>



                {% block sonata_page_breadcrumb %}
                    <div class="row">
                        <div class="col-md-12">
                            {% if sonata_seo_context is not defined %}
                                {% set sonata_seo_context = 'homepage' %}
                            {% endif %}
                        </div>
                    </div>
                {% endblock %}

                <div class="row">
                    <div class="col-md-12">
                        {% block page_content %}
                            {% if content is defined %}
                                {{ content|raw }}
                            {% else %}
                                {% set content = block('content') %}
                                {% if content|length > 0 %}
                                    {{ content|raw }}
                                {% elseif page is defined %}
                                    {{ sonata_page_render_container('content', page) }}
                                {% endif %}
                            {% endif %}
                        {% endblock %}
                    </div>
                </div>


                <footer class="row">
                    {{ sonata_page_render_container('footer', 'global') }}
                </footer>

            </div>
        </div>
    </div>
{% endblock %}
', 'AppBundle::avc_www_layout.html.twig')
        in /var/www/intrinfo/app/cache/dev/classes.php line 3758

    at Twig_Environment->compileSource('{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}
{% extends 'SonataPageBundle::base_layout.html.twig' %}

{% block sonata_page_container %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1" id="superglobal">

                

                <div class="row">
                    <div class="col-md-12">
                        {{ sonata_page_render_container('header', 'global') }}
                    </div>
                </div>



                {% block sonata_page_breadcrumb %}
                    <div class="row">
                        <div class="col-md-12">
                            {% if sonata_seo_context is not defined %}
                                {% set sonata_seo_context = 'homepage' %}
                            {% endif %}
                        </div>
                    </div>
                {% endblock %}

                <div class="row">
                    <div class="col-md-12">
                        {% block page_content %}
                            {% if content is defined %}
                                {{ content|raw }}
                            {% else %}
                                {% set content = block('content') %}
                                {% if content|length > 0 %}
                                    {{ content|raw }}
                                {% elseif page is defined %}
                                    {{ sonata_page_render_container('content', page) }}
                                {% endif %}
                            {% endif %}
                        {% endblock %}
                    </div>
                </div>


                <footer class="row">
                    {{ sonata_page_render_container('footer', 'global') }}
                </footer>

            </div>
        </div>
    </div>
{% endblock %}
', 'AppBundle::avc_www_layout.html.twig')
        in /var/www/intrinfo/app/cache/dev/classes.php line 3634

    at Twig_Environment->loadTemplate('AppBundle::avc_www_layout.html.twig')
        in /var/www/intrinfo/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php line 126

    at Symfony\Bridge\Twig\TwigEngine->load('AppBundle::avc_www_layout.html.twig')
        in /var/www/intrinfo/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php line 50

    at Symfony\Bridge\Twig\TwigEngine->render('AppBundle::avc_www_layout.html.twig', array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(Page), 'site' => object(Site)))
        in /var/www/intrinfo/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php line 72

    at Symfony\Bundle\TwigBundle\TwigEngine->render('AppBundle::avc_www_layout.html.twig', array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(Page), 'site' => object(Site)))
        in /var/www/intrinfo/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php line 97

    at Symfony\Bundle\TwigBundle\TwigEngine->renderResponse('AppBundle::avc_www_layout.html.twig', array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(Page), 'site' => object(Site)), object(Response))
        in /var/www/intrinfo/app/cache/dev/classes.php line 12310

    at Sonata\PageBundle\Page\TemplateManager->renderResponse('avcwww', array('page' => object(Page), 'site' => object(Site)), object(Response))
        in /var/www/intrinfo/app/cache/dev/classes.php line 12223

    at Sonata\PageBundle\Page\Service\DefaultPageService->execute(object(Page), object(Request), array('page' => object(Page), 'site' => object(Site)), object(Response))
        in /var/www/intrinfo/app/cache/dev/classes.php line 12162

    at Sonata\PageBundle\Page\PageServiceManager->execute(object(Page), object(Request), array(), null)
        in  line 

    at call_user_func_array(array(object(PageServiceManager), 'execute'), array(object(Page), object(Request), array(), null))
        in /var/www/intrinfo/app/bootstrap.php.cache line 3109

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /var/www/intrinfo/app/bootstrap.php.cache line 3071

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /var/www/intrinfo/app/bootstrap.php.cache line 3222

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Request), '1', true)
        in /var/www/intrinfo/app/bootstrap.php.cache line 2444

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /var/www/intrinfo/web/app_dev.php line 25
