### ISSUE TITLE
using the simple formatter widget in block does not save content using block in sonata page bundle

### ISSUE THREAD

**Issue by lordrhodos** [sonata-project/SonataFormatterBundle#125]
Hi there,

I have a project using the sonata admin and page bundle. I've created a custom block defining a field as "sonata_simple_formatter_type". Rendering of the CKEditor is working flawless, but it does not save the correct content when I try to create or update the block in the pages composer mode (e.g. http:/example.com/app_dev.php/admin/sonata/page/page/48/compose)

When I access the the block directly via the crud admin form (e.g. http:/example.com/app_dev.php/admin/sonata/page/block/440/edit?composer=1) there is no problem at all and I can update and create the content as needed.

I was able to debug the php side, so I know that the request in the latter case does not contain the updates made in the ckeditor for this form field.

**Comment by lordrhodos** [comment]
I was able to fix this bug by updating the **sonata_simple_formatter_type_widget** block in the *formatter.html.twig* template:

```
{% block sonata_simple_formatter_type_widget %}

    <!-- widget: sonata_simple_formatter_type_widget -->

    {{ form_widget(form) }}

    <script>
        jQuery(document).ready(function() {
            // This code requires CKEDITOR and jQuery MarkItUp
            if (typeof CKEDITOR === 'undefined' || jQuery().markItUp == undefined) {
                return;
            }

            var elms = jQuery('#{{ form.vars.id }}'),
		            editor = false;

            {% if format == 'textile' %}
                elms.markItUp(markitup_sonataTextileSettings);
            {% elseif format == 'markdown' %}
                elms.markItUp(markitup_sonataMarkdownSettings);
            {% elseif format == 'bbcode' %}
                elms.markItUp(markitup_sonataBBCodeSettings);
            {% elseif format == 'rawhtml' %}
                elms.markItUp(markitup_sonataHtmlSettings);
            {% elseif format == 'richhtml' %}
                editor = {{ ckeditor_replace(form.vars.id, ckeditor_configuration) }};
            {% endif %}

            var parent = elms.parents('div.markItUp');

            if (parent) {
                parent.addClass('{{ format }}');
            }

	        elms.parents("form").on('submit', function (event) {
		        if (editor) {
			        editor.updateElement();
		        }
	        });

        });
    </script>
{% endblock sonata_simple_formatter_type_widget %}
```

**Comment by OskarStark** [comment]
@lordrhodos which version are you using?

if this is still a problem, can you please provide a PR? That would be awesome :+1:

**Comment by lordrhodos** [comment]
@OskarStark I am using the ```dev-master``` and I am wondering if the option 

    ivory_ck_editor:
        input_sync: true 

described in the [IvoryCKEditor docs](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/usage.md#synchronize-the-textarea) would solve the issue as well. In my installation I get an error when I activate it, and it looks like the feature has been introduced in the 3.x branch, while the dev-master of the formatter bundle is using version 2.5.2.
