### ISSUE TITLE
Unfortunately does not work with Symfony 3.0.1

### ISSUE THREAD

**Issue by sinevar** [sonata-project/SonataFormatterBundle#133]
On master branch, in composer you stated:

"symfony/form": "~2.3|~3.0",

but this requires: "symfony/options-resolver: ~2.8|~3.0" and unfortunately for your code, OptionsResolverInterface has been removed, while you still use it in following form:

https://github.com/sonata-project/SonataFormatterBundle/blob/master/Form/Type/SimpleFormatterType.php#L60

In order to make it working I had to:

1) Change 
use Symfony\Component\OptionsResolver\OptionsResolverInterface 
to
use Symfony\Component\OptionsResolver\OptionsResolver; 

2) Change
public function setDefaultOptions(OptionsResolverInterface $resolver)
to
public function configureOptions(OptionsResolver $resolver)

I'm almost sure that another form, FormatterType may be affected by similar issue.

P.S: If you want, I can create PR to fix it, cause I really need it for my project :)

**Comment by nlzet** [comment]
@sinevar can you make a PR for this. I'm currently looking into a few Sonata bundles for making it Sf3.0 compatible. This is another step forward

**Comment by Th3Mouk** [comment]
@sinevar commits for 3.x symfony have been merged in february. Do you have any other problem ?

**Comment by greg0ire** [comment]
No answer. Closing
