### ISSUE TITLE
Could not load type "sonata_simple_formatter_type" 

### ISSUE THREAD

**Issue by kakoma** [sonata-project/SonataFormatterBundle#134]
Hi there,
I'm running Symfony CMF with Sonata admin. Following [these installation instructions and using field type `sonata_simple_formatter_type`](https://sonata-project.org/bundles/formatter/master/doc/reference/formatter_widget.html#simple-formatter-wiget) results in the error:
`Could not load type "sonata_simple_formatter_type"`

The issue is that installation using `composer require sonata-project/formatter-bundle` retrieves the latest version, `^2.3`. That version though, does not have the custom field type,`sonata_simple_formatter_type`. The field type is on the master branch

To resolve this, the field type could be added to a new release, 2.3.x so that all installations going forward don't run into this.
In the interim though, those running into the issue can require `@dev-master`

**Comment by kakawi** [comment]
thank you. it's work )

**Comment by kakoma** [comment]
Awesome! You are welcome

**Comment by rYsvelain** [comment]
Sadly, Sonata News Bundle requires Formatter Bundle in 2.3 version

**Comment by greg0ire** [comment]
I guess you can still require 2.3@dev in the composer manifest of your project.

**Comment by molarro** [comment]
Adding 2.3@dev in composer.json have solved the problem. Thank You!

**Comment by nbtai** [comment]
2.3@dev just  requires symfony/symfony >=2.3,<2.4-dev, I'm using "symfony 2.8.*"
Who know that what version of sonata-formatter-bundle  satisfiable for symfony >=2.7

**Comment by core23** [comment]
3.x

**Comment by nbtai** [comment]
@core23 you can not upgrade the to 3.x, because at the current, we use sonatabundle 2.x not 3.x, 3.x is not stable.

**Comment by Soullivaneuh** [comment]
@nbtai 3.x **is** stable: https://github.com/sonata-project/SonataFormatterBundle/releases/tag/3.0.1

2.x is not maintained anymore.

**Comment by nbtai** [comment]
@Soullivaneuh sonataFormatterBundle 3.x can not install by sonataCoreBundle ~2.2 or 2.3 and sonataUserBundle 2.2.4, I'm using its, I'm getting the error when trying install via composer.

**Comment by Soullivaneuh** [comment]
@nbtai So install needed version of the other too (3.x for all ATM).

All the information are on respective `composer.json` files. Just read them and update your dependency.

Legacy version won't be maintained.

**Comment by nbtai** [comment]
@Soullivaneuh It's seem that I can not use the SonataFormatterBundle for CKeditor field.

Cause I'm using Symfony 2.8 and sonataAdminBundle 2.3. 

https://github.com/sonata-project/SonataAdminBundle/issues/3596

**Comment by Soullivaneuh** [comment]
> Cause I'm using Symfony 2.8 and sonataAdminBundle 2.3.

So use admin-bundle **3.x**!

2.x version of admin-bundle is deprecated and not maintained too.

Please read `composer.json` files.
