### ISSUE TITLE
Unknown "ckeditor_widget" function

### ISSUE THREAD

**Issue by aimeric** [sonata-project/SonataFormatterBundle#149]
After update all my bundle with composer i'm have this error:

```Unknown "ckeditor_widget" function. Did you mean "ckeditor_plugin" in "SonataFormatterBundle:Form:formatter.html.twig" at line 58?```

i think there is a problem with SonataFormatterBundle

this is my composer.json

```"require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "egeloen/ckeditor-bundle": "~2.2",
        "sonata-project/formatter-bundle": "dev-master",
        "sonata-project/page-bundle": "dev-master"```

This is the line 58 in "SonataFormatterBundle:Form:formatter.html.twig" : 

    ```{{ source_id }}_rich_instance = {{
                            ckeditor_widget(form.children[source_field].vars.id, ckeditor_configuration)
                        }};```

Any idea how  how to fix this issue ?

**Comment by Th3Mouk** [comment]
could you send the result of `composer show -i` please ?

**Comment by aimeric** [comment]
Hey Th3Mouk , It's seems like there is a problem with the dev-master version of ckeditor-bundle. so i downgrade from "egeloen/ckeditor-bundle": "dev-master", to "egeloen/ckeditor-bundle": "3.0", and it works perfectly. Thank you  :)
