### ISSUE TITLE
Unknown "ckeditor_widget" function

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/SonataFormatterBundle#150]
Unknown "ckeditor_widget" function. Did you mean "ckeditor_plugin" in SonataFormatterBundle:Form:formatter.html.twig at line 58

sonata-project/formatter-bundle  dev-master a665525
egeloen/ckeditor-bundle 2.5.2

**Comment by greg0ire** [comment]
k

**Comment by Th3Mouk** [comment]
@stphnpt you need to `composer update`, because `ckeditor_widget` is only available in 3.x version of CKEditorBundle

**Comment by Th3Mouk** [comment]
@greg0ire i think you can close too
