### ISSUE TITLE
Update IvoryCKEditorBundle to version 4.x.

### ISSUE THREAD

**Issue by YaoOcelotl** [sonata-project/SonataFormatterBundle#151]
IvoryCKEditorBundle 4.0.0 was released on Dec 6, 2015 
IvoryCKEditorBundle 4.0.1 was released on Dec 9, 2015

**Comment by Th3Mouk** [comment]
https://github.com/sonata-project/SonataFormatterBundle/pull/148

**Comment by Th3Mouk** [comment]
@greg0ire you can close it 👍
