### ISSUE TITLE
Compatible to SonataAdmin 3.x

### ISSUE THREAD

**Issue by scuben** [sonata-project/SonataFormatterBundle#157]
Is there any timeline or checklist to make this bundle ready to use together with SonataAdminBundle 3.x? I tried to install the 2.4.x which would work with sf3 but still relies on older block and core bundle.

**Comment by greg0ire** [comment]
https://github.com/sonata-project/SonataAdminBundle/issues/3731

**Comment by Soullivaneuh** [comment]
@scuben Work in progress. You can already use **unstable** `3.x-dev` version of classification-bundle.

A stable version should be pushed this week-end.

**Comment by scuben** [comment]
@Soullivaneuh Thank you, looking forward to it. Project still wip, so no need to rush :)

**Comment by Soullivaneuh** [comment]
v3.0.0 is out: https://github.com/sonata-project/SonataFormatterBundle/releases/tag/3.0.0

Happy coding! :+1:
