### ISSUE TITLE
FatalErrorException in FormatterBlockService.php line 86:

### ISSUE THREAD

**Issue by aimeric** [sonata-project/SonataFormatterBundle#174]
Hi,

After update my composer.json i got this error:

> FatalErrorException in FormatterBlockService.php line 86: Compile Error: Declaration of Sonata\FormatterBundle\Block\FormatterBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block)

How can i fix it ?

This is my composer:

```
        "sonata-project/formatter-bundle": "2.x-dev",
        "egeloen/ckeditor-bundle": "2.3.0",
        "sonata-project/user-bundle": "3.x-dev",
        "sonata-project/page-bundle": "dev-master",
        "sonata-project/core-bundle": "3.x-dev as 2.4",
        "sonata-project/admin-bundle": "3.x-dev as 2.4",
        "sonata-project/doctrine-orm-admin-bundle": "3.x-dev as 2.4",
        "sonata-project/block-bundle": "3.x-dev as 2.4",
        "sonata-project/datagrid-bundle": "2.2.*@dev",
        "sonata-project/easy-extends-bundle": "~2.1",
        "sonata-project/seo-bundle":  "2.0.*@dev",
        "sonata-project/cache-bundle": "2.1.*",
        "sonata-project/comment-bundle": "~2.2@dev",
        "sonata-project/notification-bundle":  "2.3.*@dev",
```

**Comment by greg0ire** [comment]
Hi, sorry but as you may already know, Sonata 2 is no longer supported. Please ask us to reopen if you still experience this with Sonata 3.
