### ISSUE TITLE
CKEditor custom plugins are not being loaded

### ISSUE THREAD

**Issue by lisectech** [sonata-project/SonataFormatterBundle#196]
#### Sonata packages
SonataFormatterBundle 3.x-dev (3.0.1)
```bash
name     : sonata-project/formatter-bundle
descrip. : Symfony SonataFormatterBundle
keywords : CKEditor, formatter, markdown, markitup, sonata
versions : * 3.x-dev
```

## Subject

CKEditor custom plugins are not being loaded in the admin panel during rendering Formatter Block in Pages. I guess this happens because PluginManager is not being passed to the FormatterType constructor.

## Steps to reproduce

Try to use SonataFormatterBundle with SonataPageBundle and render sonata.formatter.block.formatter in the Composer (in the SonataPage context, not the package manager).

## Quick fix
I came up with a quick fix that requires modification of 3 files. I don't know if it is the best solution, but worked for me:

**sonata-project/formatter-bundle/Resources/config/form.xml after line 8**
Pass the PluginManager to the sonata.formatter.form.type.selector service:
```xml
[...]
    <argument type="service" id="ivory_ck_editor.config_manager"/>
    <argument type="service" id="ivory_ck_editor.plugin_manager"/>
[...]
```

**sonata-project/formatter-bundle/Resources/views/Form/formatter.html.twig after line 55**
Render plugins in the view:
```twig
[...]
case 'richhtml':
    {% for plugin_name, plugin in ckeditor_plugins %}
        {{ ckeditor_plugin(plugin_name, plugin) }}
    {% endfor %}
[...]
```

**sonata-project/formatter-bundle/Form/Type/FormatterType.php**
Add the PluginManagerInterface to the constructor arguments and pass plugins to the view.
```php
[...]
    /**
     * @var PluginManagerInterface
     */
    protected $pluginManager;

[...]
    /**
     * Constructor.
     *
     * @param Pool $pool A Formatter Pool service
     * @param TranslatorInterface $translator A Symfony Translator service
     * @param ConfigManagerInterface $configManager An Ivory CKEditor bundle configuration manager
     * @param PluginManagerInterface $pluginManager
     */
    public function __construct(Pool $pool, TranslatorInterface $translator, ConfigManagerInterface $configManager, PluginManagerInterface $pluginManager)
    {
        $this->pool = $pool;
        $this->translator = $translator;
        $this->configManager = $configManager;
        $this->pluginManager = $pluginManager;
    }
[...]
        // buildView() method:
        $view->vars['ckeditor_plugins'] = $this->pluginManager->getPlugins();
[...]
```

**Comment by Slavenin** [comment]
What status this PR? This very actual for me!

**Comment by core23** [comment]
Please be patient. There is an open PR (https://github.com/sonata-project/SonataFormatterBundle/pull/197) which is in the review process.

**Comment by Slavenin** [comment]
tnx
