### ISSUE TITLE
Widget broken with PR #205

### ISSUE THREAD

**Issue by hug963** [sonata-project/SonataFormatterBundle#210]
## Subject
This PR https://github.com/sonata-project/SonataFormatterBundle/pull/205 broke the main widget in the page composer.

The simple widget is not affected as it was not updated.

I get this error in the admin:

> The option "choice_translation_domain" does not exist. Defined options are: "action", "allow_extra_fields", "attr", "auto_initialize", "block_name", "by_reference", "cascade_validation", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_provider", "csrf_token_id", "csrf_token_manager", "data", "data_class", "disabled", "empty_data", "error_bubbling", "error_mapping", "extra_fields_message", "horizontal_input_wrapper_class", "horizontal_label_class", "horizontal_label_offset_class", "inherit_data", "intention", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "label_render", "mapped", "max_length", "method", "pattern", "post_max_size_message", "property_path", "read_only", "required", "sonata_admin", "sonata_field_description", "sonata_help", "static_control", "translation_domain", "trim", "validation_groups", "virtual".

**Comment by greg0ire** [comment]
I assign @core23 because he has the most context about this IMO.
