### ISSUE TITLE
Improve FormatterType with single formatter type

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataFormatterBundle#212]
When using the `FormatterType` with a single formatter, we got an ugly hack to change the type selector form `choice` to hidden. This should be improved.

https://github.com/sonata-project/SonataFormatterBundle/blob/3.x/Form/Type/FormatterType.php#L97-L104

**Comment by greg0ire** [comment]
I don't even know why we add a hidden field : if there is only one possibility, there is no need to submit anything, the action we post to can figure it out.
