### ISSUE TITLE
'sonata_formatter_type' does not initially selects proper content format

### ISSUE THREAD

**Issue by TheCelavi** [sonata-project/SonataFormatterBundle#236]
See: [https://github.com/sonata-project/sandbox/issues/596](https://github.com/sonata-project/sandbox/issues/596)

## Text from issue:

Description: SonataNewsBundle uses 'sonata_formatter_type' for content field. When you save content with any other format, on edit, saved format is not selected.

Steps to reproduce a bug:

1. Go to sonata demo http://demo.sonata-project.org/ and create container, login into administration, go to dashboard (backend), path:  [domain]/admin/app/news-post/list
2. Open any news post for editing
3. Edit content by changing formatting type for field Content to, per  example "richhtml"
4. Click "Update" button

Expected result: Content is saved with new formatter, formatter is initially selected, CK editor is displayed on load.

Actual result: HTML code is displayed in Textarea, "markdown" content formatter is selected.

## Additional notes

I have tried to figure out where to search for issue, last thing what I have found is that `Sonata\FormatterBundle\Form\Type\FormatterType` does not provides a value for currently in-database saved formatter. I need help to figure this one out.

**Comment by TheCelavi** [comment]
Hm, for some reason, PRE_SET_DATA event does not give any value for $event->getData() ?

This is behaving very strange... ?

**Comment by iMultis** [comment]
Confirm this bug. Content formatter is saved properly into database's content_formatter field, nevertheless every time I open this page I get default value, not value selected earlier and stored in DB.

**Comment by iMultis** [comment]
After a quick look through I have found following rows in `Sonata\FormatterBundle\Form\Type\FormatterType` class:
```
    if (!array_key_exists('data', $options['format_field_options']) ||
         !array_key_exists($options['format_field_options']['data'], $this->pool->getFormatters())) {
        $options['format_field_options']['data'] = $this->pool->getDefaultFormatter();
    }
```
They force content_formatter's field data to `default_formatter` value, specified in bundle's configuration. Removing them seems to solve the problem.

**Comment by tonyellow** [comment]
I have exacttly the same issue om latest version so I don't think this issue should be closed.
