### ISSUE TITLE
Twig 2.x compatibility

### ISSUE THREAD

**Issue by Nek-** [sonata-project/SonataFormatterBundle#237]
## Subject

Creating a project with latest versions of Symfony means getting twig 2.x. This bundle need explicitly twig 1.x.

## Actual results

> Error: Class Sonata\FormatterBundle\Twig\Loader\LoaderSelector contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Twig_LoaderInterface::getSourceContext, Twig_LoaderInterface::exists)

The point is not only to fix the issue of missing methods but SonataFormatterBundle also uses `Twig_Loader_String` that doesn't exist anymore.

## Potential temporary fix

Otherwise, Symfony [doesn't specify a specific version of Twig](https://github.com/symfony/symfony-standard/blob/master/composer.json#L24). Adding one in the `composer.json` of this project may be a good idea.

**Comment by greg0ire** [comment]
See also : https://github.com/sonata-project/SonataFormatterBundle/pull/231#issuecomment-281054417

**Comment by greg0ire** [comment]
It looks like we lack coverage, but I don't think we should require 1.x again, unless failing tests are added. The best solution might be to actually fix the issues.

**Comment by greg0ire** [comment]
I had a quick look at the loader, it looks like it is a composite loader, so the implementation could just forward calls to composing loaders. [Here is what to do for the loader string](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Loader/String.php#L12). cc @magedan @core23

**Comment by greg0ire** [comment]
`Twig_Loader_Array` does not look like a viable solution : https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Loader/Array.php#L20

**Comment by Nek-** [comment]
Closed by #239
