### ISSUE TITLE
Problems running composer install/update

### ISSUE THREAD

**Issue by diogorodriguesc** [sonata-project/SonataFormatterBundle#244]
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.13.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.1  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.2.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/formatter-bundle          3.2.0  Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/user-bundle               3.2.2  Symfony SonataUserBundle
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v2.8.18 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.3  Symfony SwiftmailerBundle
symfony/symfony            v2.8.18 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.14 (cli) (built: Jan 17 2017 19:30:34) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethan
```

## Subject

Problems in two classes. 
- Sonata\FormatterBundle\Twig\Loader\LoaderSelector is implementing an Interface and is not implementing Twig_LoaderInterface::exists and LoaderInterface::getSourceContext methods. 
- DependencyInjection/SonataFormatterExtension.php on createEnvironment method Twig_Loader_String Class is being used but it is deprecated.

## Steps to reproduce
Trying to do composer install / update

## Expected results
Succesfull Installation / update.

## Actual results

 Fatal error: Class Sonata\FormatterBundle\Twig\Loader\LoaderSelector contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Twig_  
  LoaderInterface::getSourceContext, Twig_LoaderInterface::exists) in /admin/vendor/sonata-project/formatter-bundle/Twig/Loader/LoaderSelector.php on line 14

Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Twig_Loader_String" from the global namespace.

**Comment by greg0ire** [comment]
I believe I fixed this on 3.x, but maybe it's not release yet.

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/SonataFormatterBundle/pull/239

**Comment by diogorodriguesc** [comment]
Do you know, when is this being released?

**Comment by greg0ire** [comment]
You can help us do it faster if you want : https://github.com/greg0ire/dev-kit/blob/b537dc06c56a7b1e2c24dae50fdf332f8bb717e0/project/CONTRIBUTING.md#minor-releases-and-patch-releases

- [ ] determine what the next version should be
- [ ] changing the UPGRADE file if needed
- [ ] compiling the CHANGELOG
