### ISSUE TITLE
FormatterBlockService does not work with sonataAdmin

### ISSUE THREAD

**Issue by Chrisvore** [sonata-project/SonataFormatterBundle#246]
#### Sonata packages
sonata-project/admin-bundle              3.14.0
sonata-project/block-bundle              3.3.1
sonata-project/cache                     1.0.7
sonata-project/cache-bundle              2.3.1
sonata-project/classification-bundle     3.3.0
sonata-project/core-bundle               3.2.0
sonata-project/datagrid-bundle           2.2.1
sonata-project/doctrine-extensions       1.0.2
sonata-project/doctrine-orm-admin-bundle 3.1.3
sonata-project/easy-extends-bundle       2.1.10 
sonata-project/exporter                  1.7.1
sonata-project/formatter-bundle          3.2.0
sonata-project/intl-bundle               2.3.0
sonata-project/media-bundle              3.5.0
sonata-project/notification-bundle       3.1.0
sonata-project/page-bundle               3.4.0
sonata-project/seo-bundle                2.1.0

#### Symfony packages

symfony-cmf/routing                      1.4.0
symfony-cmf/routing-bundle               1.4.0
symfony/assetic-bundle                   v2.8.1
symfony/monolog-bundle                   v2.12.1
symfony/phpunit-bridge                   v3.2.6
symfony/polyfill-apcu                    v1.3.0
symfony/polyfill-intl-icu                v1.3.0
symfony/polyfill-mbstring                v1.3.0
symfony/polyfill-php54                   v1.3.0
symfony/polyfill-php55                   v1.3.0
symfony/polyfill-php56                   v1.3.0
symfony/polyfill-php70                   v1.3.0
symfony/polyfill-util                    v1.3.0
symfony/security-acl                     v3.0.0
symfony/swiftmailer-bundle               v2.5.3
symfony/symfony                          v2.8.18 

#### PHP version

PHP 7.0.17-1+deb.sury.org~xenial+4

## Subject

It seems that the service should extends `Sonata\BlockBundle\Block\Service\AbstractAdminBlockService` instead of `Sonata\BlockBundle\Block\Service\AbstractBlockService` as the first extends the second. If not, you get Exception : Attempted to call an undefined method named "validateBlock" of class "Sonata\FormatterBundle\Block\FormatterBlockService" when trying to edit an admin block or Attempted to call an undefined method named "buildCreateForm" of class "Sonata\FormatterBundle\Block\FormatterBlockService".
Did you mean to call "buildEditForm"?

## Steps to reproduce

Does not work out of the box

## Expected results

A form to create or edit

## Actual results

Attempted to call an undefined method named "buildCreateForm" of class "Sonata\FormatterBundle\Block\FormatterBlockService".
Did you mean to call "buildEditForm"?

**Comment by jordisala1991** [comment]
This is already solved on: https://github.com/sonata-project/SonataFormatterBundle/pull/235

But it is not tagged yet.

**Comment by Chrisvore** [comment]
Ok, can't wait to have it tagged :)

**Comment by OskarStark** [comment]
I requested a release internally
