### ISSUE TITLE
Template "<html><p>...</p></html>" is not defined

### ISSUE THREAD

**Issue by faizanahmad** [sonata-project/SonataFormatterBundle#253]
#### Sonata packages

```bash
$ composer show sonata-project/*

sonata-project/admin-bundle              3.18.2  The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2   Symfony SonataBlockBundle
sonata-project/cache                     1.0.7   Cache library
sonata-project/core-bundle               3.4.0   Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1   Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.4   Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.1   Lightweight Exporter library
sonata-project/formatter-bundle          3.2.1   Symfony SonataFormatterBundle
```
#### Symfony packages

```bash
$ composer show symfony/*
# Put the result here.
symfony/monolog-bundle                   v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge                   v3.2.8  Symfony PHPUnit Bridge
symfony/polyfill-apcu                    v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu                v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring                v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                   v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70                   v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                    v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl                     v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle               v2.6.2  Symfony SwiftmailerBundle
symfony/symfony                          v3.1.10 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
```

## Subject

I'm showing rich text editor on a field using following formMapper.  

`$formMapper->add('body', 'sonata_formatter_type', array(
                       'event_dispatcher' => $formMapper->getFormBuilder()
                                                        ->getEventDispatcher(),
                       'format_field' => 'formattedBody',
                       'format_field_options' => array(
                           'choices' => array('richhtml'),
                           'data' => 'richhtml',
                       ),
                       'source_field' => 'body',
                       'source_field_options' => array(
                           'attr' => array(
                               'class' => 'span10',
                               'rows' => 20,
                           ),
                       ),
                       'listener' => true,
                       'target_field' => 'body',
                   ))`
on form save i get 500 error `Template "<html><p>...</p></html>" is not defined`
On localhost same code works fine but localhost is running php 5.6, Live server is running PHP7 
Let me know if there is any workaround 

## Expected results
Form should save

**Comment by greg0ire** [comment]
Do you think this is related to https://github.com/sonata-project/SonataFormatterBundle/pull/252 ?

**Comment by core23** [comment]
We need a patch release

**Comment by greg0ire** [comment]
So this means the workaround for you is either to use `3.x@dev` or  to blacklist `3.2.0` and `3.2.1`

**Comment by faizanahmad** [comment]
`^3.1,!=3.2.0,!=3.2.1` works fine. Thanks alot @greg0ire 👍

**Comment by greg0ire** [comment]
No problem, and consider using `composer install` in production, you shouldn't have differences with your dev env. Likewise consider using `docker` to have php7 for this particular project, otherwise you will have many other bad surprises.
