### ISSUE TITLE
Can't install with sf 3.3

### ISSUE THREAD

**Issue by borjadinamic** [sonata-project/SonataFormatterBundle#269]
#### Sonata packages

```
sonata-project/admin-bundle              3.23.0             = 3.23.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2              ! 3.4.0              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              = 1.0.7              Cache library
sonata-project/core-bundle               3.4.0              ! 3.5.1              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              = 2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              = 1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.6              ! 3.1.7              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0              = 2.2.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              = 1.7.1              Lightweight Exporter library
sonata-project/user-bundle               dev-master fca7672 ! dev-master 727b0bf Symfony SonataUserBundle

```

#### Symfony packages

```
symfony/monolog-bundle     v3.1.0 = v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.8 ! v3.3.9 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.5.0 = v1.5.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.5.0 = v1.5.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.5.0 = v1.5.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.5.0 = v1.5.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.5.0 = v1.5.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.5.0 = v1.5.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 = v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.3 ~ v3.0.4 Symfony SwiftmailerBundle
symfony/symfony            v3.3.8 ! v3.3.9 The Symfony PHP framework

```

#### PHP version

```
PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

## Steps to reproduce
Just run `composer require sonata-project/formatter-bundle`

## Expected results
Bundle installed

## Actual results

> Using version ^3.2 for sonata-project/formatter-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
>
>   Problem 1
>     - Conclusion: don't install sonata-project/formatter-bundle 3.2.3
>     - Conclusion: don't install sonata-project/formatter-bundle 3.2.2
>     - Conclusion: don't install sonata-project/formatter-bundle 3.2.1
>     - Conclusion: remove egeloen/ckeditor-bundle 6.0.1
>     - Installation request for sonata-project/formatter-bundle ^3.2 -> satisfiable by sonata-project/formatter-bundle[3.2.0, 3.2.1, 3.2.2, 3.2.3].
>     - Conclusion: don't install egeloen/ckeditor-bundle 6.0.1
>     - sonata-project/formatter-bundle 3.2.0 requires egeloen/ckeditor-bundle ^4.0 -> satisfiable by egeloen/ckeditor-bundle[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6].
>     - Can only install one of: egeloen/ckeditor-bundle[4.0.0, 6.0.1].
>     - Can only install one of: egeloen/ckeditor-bundle[4.0.1, 6.0.1].
>     - Can only install one of: egeloen/ckeditor-bundle[4.0.2, 6.0.1].
>     - Can only install one of: egeloen/ckeditor-bundle[4.0.3, 6.0.1].
>     - Can only install one of: egeloen/ckeditor-bundle[4.0.4, 6.0.1].
>     - Can only install one of: egeloen/ckeditor-bundle[4.0.5, 6.0.1].
>     - Can only install one of: egeloen/ckeditor-bundle[4.0.6, 6.0.1].
>     - Installation request for egeloen/ckeditor-bundle (locked at 6.0.1) -> satisfiable by egeloen/ckeditor-bundle[6.0.1].

**Comment by greg0ire** [comment]
Sounds like we need to change this: https://github.com/sonata-project/SonataFormatterBundle/blob/7f5815560d7b41327153a0168a0d24ed9c17778f/composer.json#L21

**Comment by borjadinamic** [comment]
Yes, i think so, because "egeloen/ckeditor-bundle (locked at 6.0.1)"

**Comment by greg0ire** [comment]
Can you work on a PR?

**Comment by borjadinamic** [comment]
This week will be impossible because of lack of time, so I have reported, if I had not sent the PR.

I hope someone can fix it as soon as possible, if not, next week I will send it.

**Comment by borjadinamic** [comment]
Done @greg0ire merge asap please. 👍
