### ISSUE TITLE
Replace Markdown Editor with SimpleMDE

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataFormatterBundle#309]
The current markdown editor is really crappy

This edtior looks more modern: https://simplemde.com/

There is also a symfony bundle: https://github.com/NobletSolutions/SimpleMDEBundle

**Comment by greg0ire** [comment]
Looks gorgeous :+1: !

**Comment by core23** [comment]
The markdown editor was removed on the master branch.

I created a new bundle for this: https://github.com/core23/CommonMarkFormatterBundle
