### ISSUE TITLE
bundle doesn't support symfony 4

### ISSUE THREAD

**Issue by gennadyx** [sonata-project/SonataFormatterBundle#324]
and mantainer of ckeditor-bundle package seems busy and don't accept pullrequests

**Comment by kunicmarko20** [comment]
We support symfony4, https://github.com/sonata-project/SonataFormatterBundle/blob/3.4.1/composer.json#L31-L33

If you are talking about IvoryCKEditorBundle, we are aware of that.

**Comment by gennadyx** [comment]
ok i see your bunlde supports symfony 4, but what to do with  ckeditor-bundle? It makes errors when i try to setup sonata/ecommerce bundle dev-master branch

**Comment by jordisala1991** [comment]
There are already a lot of issues on the ckeditor-bundle to support Symfony4, we support it, and they will when someone takes over the bundle.

This issue does not belong here
