### ISSUE TITLE
can you update requirements to fork of ckeditor bundle

### ISSUE THREAD

**Issue by gennadyx** [sonata-project/SonataFormatterBundle#325]
Look this comment:
https://github.com/egeloen/IvoryCKEditorBundle/pull/330#issuecomment-355823587
and twit by Eric GELOEN:
https://twitter.com/egeloen/status/931240338467049472

**Comment by jordisala1991** [comment]
AFAIK you can use use the fork of the ckeditor in your composer.json.

Closing because we cant switch to unstable dependency like that.
