### ISSUE TITLE
CKEditor on Symfony4

### ISSUE THREAD

**Issue by ZeusInTexas** [sonata-project/SonataFormatterBundle#345]
Hello,

Is there any plan to use the overtaken friendsofsymfony/ckeditor-bundle (instead of egeloen/ckeditor-bundle), so the bundle is actually fully compatible with Symfony4?

Thanks,
Matt.

**Comment by kunicmarko20** [comment]
Did you read our new installation page? https://sonata-project.org/bundles/formatter/3-x/doc/reference/installation.html

Closing as this is already possible.

**Comment by ZeusInTexas** [comment]
Thanks, I've seen that, but is there any plan other than such kind of 'hack'?

**Comment by kunicmarko20** [comment]
That is the only way that 3.x would work without making a BC Break. Next major version (4.x) will be compatible with just fosckeditor.

**Comment by ZeusInTexas** [comment]
Got it. Thanks for the insight!
