### ISSUE TITLE
Lots of deprecations

### ISSUE THREAD

**Issue by lukepass** [sonata-project/SonataFormatterBundle#407]
### Environment
Website with Symfony 3.4

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.48.1 3.48.3 The missing Symfony A...
sonata-project/block-bundle              3.15.0 3.15.0 Symfony SonataBlockBu...
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.16.2 3.17.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  3.0.0  Symfony SonataDatagri...
sonata-project/doctrine-extensions       1.2.0  1.3.0  Doctrine2 behavioral ...
sonata-project/doctrine-orm-admin-bundle 3.8.3  3.9.0  Symfony Sonata / Inte...
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExt...
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter ...
sonata-project/formatter-bundle          4.1.2  4.1.2  Symfony SonataFormatt...
sonata-project/media-bundle              3.19.1 3.20.0 Symfony SonataMediaBu...
sonata-project/user-bundle               4.3.0  4.3.0  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/contracts             v1.0.2  v1.1.0  A set of abstractions extracte...
symfony/monolog-bundle        v3.3.1  v3.3.1  Symfony MonologBundle
symfony/phpunit-bridge        v4.2.6  v4.2.8  Symfony PHPUnit Bridge
symfony/polyfill-apcu         v1.11.0 v1.11.0 Symfony polyfill backporting a...
symfony/polyfill-ctype        v1.11.0 v1.11.0 Symfony polyfill for ctype fun...
symfony/polyfill-intl-icu     v1.11.0 v1.11.0 Symfony polyfill for intl's IC...
symfony/polyfill-mbstring     v1.11.0 v1.11.0 Symfony polyfill for the Mbstr...
symfony/polyfill-php56        v1.11.0 v1.11.0 Symfony polyfill backporting s...
symfony/polyfill-php70        v1.11.0 v1.11.0 Symfony polyfill backporting s...
symfony/polyfill-util         v1.11.0 v1.11.0 Symfony utilities for portabil...
symfony/security-acl          v3.0.2  v3.0.2  Symfony Security Component - A...
symfony/swiftmailer-bundle    v2.6.7  v3.2.6  Symfony SwiftmailerBundle
symfony/symfony               v3.4.25 v4.2.8  The Symfony PHP framework
symfony/webpack-encore-bundle v1.5.0  v1.5.0  Integration with your Symfony ...
```

#### PHP version

```
$ php -v
PHP 7.2.17-1+ubuntu16.04.1+deb.sury.org+3 (cli) (built: Apr 10 2019 10:50:19) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.17-1+ubuntu16.04.1+deb.sury.org+3, Copyright (c) 1999-2018, by Zend Technologies
```

## Subject

Hello, this bundle contains a lot of deprecations after a flesh install:

-	The FOS\CKEditorBundle\DependencyInjection\CompilerResourceCompilerPass is deprecated since 1.x and will be removed with the 2.0 release.
-	The FOS\CKEditorBundle\DependencyInjection\CompilerTemplatingCompilerPass is deprecated since 1.x and will be removed with the 2.0 release.
-	Using the "Twig_Extension" class is deprecated since Twig version 2.7, use "Twig\Extension\AbstractExtension" instead.
-	The Sonata\AdminBundle\Command\CreateClassCacheCommand class is deprecated since version 3.39.0 and will be removed in 4.0.
-	The Sonata\CoreBundle\Model\PageableManagerInterface class is deprecated since version 3.12.0 and will be removed in 4.0. Use Sonata\DatagridBundle\Pager\PageableInterface instead.
-	The Sonata\CoreBundle\Model\ManagerInterface class is deprecated since version 3.12.0 and will be removed in 4.0. Use Sonata\Doctrine\Model\ManagerInterface instead.
-	The Sonata\CoreBundle\Model\BaseEntityManager class is deprecated since version 3.12.0 and will be removed in 4.0. Use Sonata\Doctrine\Entity\BaseEntityManager instead.
-	The FOS\CKEditorBundle\ModelConfigManager is deprecated since 1.x and will be removed with the 2.0 release.
-	The FOS\CKEditorBundle\ModelConfigManagerInterface is deprecated since 1.x and will be removed with the 2.0 release.
-	The FOS\CKEditorBundle\ModelPluginManager is deprecated since 1.x and will be removed with the 2.0 release.
-	The FOS\CKEditorBundle\ModelPluginManagerInterface is deprecated since 1.x and will be removed with the 2.0 release.
-	The FOS\CKEditorBundle\ModelStylesSetManager is deprecated since 1.x and will be removed with the 2.0 release.
-	The FOS\CKEditorBundle\ModelStylesSetManagerInterface is deprecated since 1.x and will be removed with the 2.0 release.
-	The FOS\CKEditorBundle\ModelTemplateManager is deprecated since 1.x and will be removed with the 2.0 release.
-	The FOS\CKEditorBundle\ModelTemplateManagerInterface is deprecated since 1.x and will be removed with the 2.0 release.
-	The FOS\CKEditorBundle\ModelToolbarManager is deprecated since 1.x and will be removed with the 2.0 release.
-	The FOS\CKEditorBundle\ModelToolbarManagerInterface is deprecated since 1.x and will be removed with the 2.0 release.
-	Using the "Twig_Loader_Array" class is deprecated since Twig version 2.7, use "Twig\Loader\ArrayLoader" instead.
-	Using the "Twig_Extension_Sandbox" class is deprecated since Twig version 2.7, use "Twig\Extension\SandboxExtension" instead.
-	Using the "Twig_Lexer" class is deprecated since Twig version 2.7, use "Twig\Lexer" instead.

Is there a way I can help getting rid of them?

Thanks.

**Comment by core23** [comment]
Can you provide a PR which removes the usage?

**Comment by lukepass** [comment]
@core23 yes I can but I'm not sure where I should intervene? Shall I just find and replace all the occurrences in the SonataCoreBundle package?

Thanks!
