### ISSUE TITLE
Document images lost

### ISSUE THREAD

**Issue by TangMonk** [sonata-project/SonataFormatterBundle#416]
in https://sonata-project.org/bundles/formatter/3-x/doc/reference/formatter_widget.html
![image](https://user-images.githubusercontent.com/3498786/62405807-da334c80-b5d4-11e9-91b8-9cd568e974f6.png)

**Comment by TangMonk** [comment]
bug still

**Comment by core23** [comment]
Can you create a PR with a fix @TangMonk ?
