### ISSUE TITLE
Upgrade FOS CKEditor dependency to 2.0

### ISSUE THREAD

**Issue by psyray** [sonata-project/SonataFormatterBundle#447]
## Feature Request

Is it possible to update the **friendsofsymfony/ckeditor-bundle** to 2.0 ?
To fix some deprecation in Symfony and prepare bundle to 5.0 compatibility

**Comment by psyray** [comment]
PR Submitted
Need review & comment

**Comment by jordisala1991** [comment]
Support for 2.0 added here: #472
