### ISSUE TITLE
always "Insert your custom content here" as content in formatter Block front end

### ISSUE THREAD

**Issue by apirastru** [sonata-project/SonataFormatterBundle#45]
Hi everybody 
I added a Sonata Formatter Block in my page on my Sonata sandbox version and even editing with success (on DB too) the content (registered with CKEditor in richhtml format) I've always the same default phrase "Insert your custom content here" on front end.. 

here some pictures : 
![capture decran 2014-01-20 a 13 32 15](https://f.cloud.github.com/assets/6448597/1954150/aa93f126-81cf-11e3-8652-12cf9ccc753f.png)
![capture decran 2014-01-20 a 13 33 24](https://f.cloud.github.com/assets/6448597/1954153/b2c25e78-81cf-11e3-9d50-d48c4092c887.png)

should I miss something or nobody use formatter block.... :)
Thanx in advance

**Comment by OskarStark** [comment]
@rande close this issue or not?

**Comment by core23** [comment]
Close!
