### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by gam6itko** [sonata-project/SonataFormatterBundle#463]
## Feature Request

Are you planning to add support for Symfon5?

**Comment by core23** [comment]
> Are you planning to add support for Symfon5?

Yes, but no one has started it. Maybe you can help @gam6itko ?

**Comment by jorrit** [comment]
A while ago I started with it on https://github.com/jorrit/SonataFormatterBundle/tree/symfony5, but the dev dependencies media-bundle and admin-bundle are not compatible with Symfony 5 yet. It appears these bundles are only necessary for the CkeditorAdminControllerTest test class, which provides 2 test functions. Perhaps the formatter-bundle functionality covered by CkeditorAdminControllerTest can be tested in a way that does not require media-bundle and admin-bundle.

**Comment by medsalah91** [comment]
Hello, Are you planning to add this issu ?

**Comment by core23** [comment]
> Hello, Are you planning to add this issu ?

*We* as the core team / reviewers are not actively working on the issue at the moment. Maybe you can help to finish this @medsalah91

**Comment by VincentLanglet** [comment]
We currently are working on the SonataMediaBundle, which is a requirement for this.

**Comment by balazscsaba2006** [comment]
@core23 Since MediaBundle has already support for `^5.3`, can this PR https://github.com/sonata-project/SonataFormatterBundle/pull/622 be merged? Do you need help with it?

**Comment by core23** [comment]
> @core23 Since MediaBundle has already support for `^5.3`, can this PR #622 be merged? Do you need help with it?

There is no stable release for the media bundle

**Comment by ger86** [comment]
I have added support por SF 5.3 in this branch: 

https://github.com/ger86/SonataFormatterBundle/tree/symfony5

It contains more changes than provided by @balazscsaba2006  to fix some errors. Do you want me to create a PR?

**Comment by VincentLanglet** [comment]
Any help on https://github.com/sonata-project/dev-kit/issues/1715 is welcomed.

But be sure to target the 5.x branch since adding support for Sonata 4/Symfony 5 will introduce some BC break I think.

**Comment by VincentLanglet** [comment]
5.x now support Sf5, feel free to try this unstable branch until we finished a stable release (it will still take some time)
