### ISSUE TITLE
No error message displayed for 'sonata_formatter_type'

### ISSUE THREAD

**Issue by awesemo** [sonata-project/SonataFormatterBundle#58]
Validation error is not displayed on the form type.

**Comment by core23** [comment]
Can you say something more. How can we reproduce this?

**Comment by Madlexx** [comment]
Hi there. You can reproduce this if chooses a  sonata_simple_formatter_type, and take  format = richhtml . If field have NotBlank rule , you take red label without message. 
![screenshot from 2016-03-11 13-38-11](https://cloud.githubusercontent.com/assets/8816085/13701145/84b7bc7c-e78e-11e5-9fef-fe753736794a.png)

But if you place something(like button) in the formatter.html.twig 
`<button class="error">Error should be</button>
    {{ form_widget(form) }}`

You take error on hover the button. 
![screen_with_button](https://cloud.githubusercontent.com/assets/8816085/13701212/010f1b12-e78f-11e5-8da3-cc849522ee26.png)

**Comment by dmarkowicz** [comment]
It works correctly with current bundles and CKEditor 4.10.0.
```
sonata-project/admin-bundle              3.37.0 
sonata-project/block-bundle              3.12.1 
sonata-project/core-bundle               3.11.2 
sonata-project/formatter-bundle          3.5.0  
```
![2018-08-05_1239](https://user-images.githubusercontent.com/1571340/43685126-6d3b7eee-98ad-11e8-8700-b31c20f51c63.png)

**Comment by dmarkowicz** [comment]
We can add a red frame to editor field to make it perfect :)
![2018-08-05_1336](https://user-images.githubusercontent.com/1571340/43685522-cdc95dd8-98b4-11e8-8d8e-5ad1325c637f.png)
