### ISSUE TITLE
Unable to generate a URL for the named route "admin_app_sonata_media_media_browser" as such route does not exist."

### ISSUE THREAD

**Issue by bartoszstrzala** [sonata-project/SonataFormatterBundle#767]
Hi,

I have problem routing just not generate.

I was try to add to routes.yaml
annot:
    resource: "@SonataFormatterBundle/Controller/CkeditorAdminController.php"
    type:     annotation

but:

root@f89ecceaa8d0:/var/www/symfony# php bin/console debug:router |grep ckeditor
root@f89ecceaa8d0:/var/www/symfony# 

$ composer show --latest 'sonata-project/*'
Direct dependencies required in composer.json:
sonata-project/admin-bundle              4.25.0 4.25.0 The missing Symfony Admin Generator
sonata-project/doctrine-orm-admin-bundle 4.13.0 4.13.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/formatter-bundle          5.3.0  5.3.0  Symfony SonataFormatterBundle
sonata-project/media-bundle              4.10.0 4.10.0 Symfony SonataMediaBundle
sonata-project/user-bundle               5.9.0  5.9.0  Symfony SonataUserBundle

Transitive dependencies not required in composer.json:
sonata-project/block-bundle              4.21.0 4.21.0 Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.2.0  Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/doctrine-extensions       2.3.0  2.3.0  Doctrine2 behavioral extensions
sonata-project/exporter                  3.1.1  3.1.1  Lightweight Exporter library
sonata-project/form-extensions           2.0.0  2.0.0  Symfony form extensions
sonata-project/twig-extensions           2.1.0  2.1.0  Sonata twig extensions

**Comment by jordisala1991** [comment]
I dont remember such configuration for the SonataFormatterBundle, we do not use annotations for routes. Please follow the official docs for installing and configuring this bundle: https://docs.sonata-project.org/projects/SonataFormatterBundle/en/5.x/reference/installation/

**Comment by bartoszstrzala** [comment]
> I dont remember such configuration for the SonataFormatterBundle, we do not use annotations for routes. Please follow the official docs for installing and configuring this bundle: https://docs.sonata-project.org/projects/SonataFormatterBundle/en/5.x/reference/installation/

Yes, I was installed from documentation - its not working.

If I remove this routes, its still not working.

**Comment by jordisala1991** [comment]
Did you install AdminBundle and MediaBundle too?
