### ISSUE TITLE
CKEditor:install does not install working version of it

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataFormatterBundle#768]
https://github.com/FriendsOfSymfony/FOSCKEditorBundle/issues/253

`bin/console ckeditor:install --tag=4.22.1` would still work.

**Comment by haivala** [comment]
Event that command stopped working now.

**Comment by rishisinghrsm** [comment]
to find bank ifsc code visit [http://ifsc-code-finder.online/]
