### ISSUE TITLE
Adding format_field_options to sonata_formatter_type causes error

### ISSUE THREAD

**Issue by ima-tech** [sonata-project/SonataFormatterBundle#79]
When I try to add the format_field_options, I get the following error:

```
Key "choices" for array with keys "attr" does not exist in SonataFormatterBundle:Form:formatter.html.twig at line 5
```

Here's my code in the admin
```
     'format_field_options' => array(
        'attr' => array('class' =>'test')
    ),
```

By looking up really quick, it seems that when we pass the 'format_field_options', it overwrites the existing array instead of merging. I'll look further into it.

**Comment by core23** [comment]
That's the normal behavior
