### ISSUE TITLE
knp-markdown-bundle update

### ISSUE THREAD

**Issue by Richard-NL** [sonata-project/SonataFormatterBundle#84]
when using assets install I get a message telling dflydev/markdown is abandoned.
Any objection in upping knp-markdown-bundle version which uses michelf/php-markdown ?

**Comment by jfgrissom** [comment]
I agree. It would be nice to not rely on an older bundle that depends on an abandoned bundle.

**Comment by jubalh** [comment]
I suppose this is right now an issue for me.
Trying to use the sonata-news bundle i am trying to get the formatter-bundle to work. however i got the message about markdown. when i want to install knp-markdown. it doesnt work.
https://bpaste.net/show/acad4bd79827
so: any news on this one?

**Comment by jordisala1991** [comment]
This is solved already
