### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by skillberto** [sonata-project/SonataFormatterBundle#85]
Hy,

I've got an error (please see on the subject), when I switch between formatters.
But this error occurs after some change, not at first, or second. I don't find the logic behind the error.

Could you please take a look at the problem. I can show you my config file(s) if it necessary.

Best regards,
Norbert

**Comment by jessevanmuijden** [comment]
:+1: we have the same problem. It works in the sandbox demo, though. Don't know what we are missing

**Comment by rande** [comment]
Can you print a stack trace ? Thanks

**Comment by jessevanmuijden** [comment]
@rande thank you for your response!

Uncaught TypeError: Cannot read property 'destroy' of undefined ckeditor.js:243 CKEDITOR.tools.extend.destroy edit:1265
(anonymous function) jquery.js:4641
m.event.dispatch jquery.js:4309 
m.event.add.r.handle jquery.js:4550 
m.event.trigger jquery.js:5260 
(anonymous function) jquery.js:383 
m.extend.each jquery.js:136 
m.fn.m.each jquery.js:5259 
m.fn.extend.trigger select2.min.js:21 
O.triggerChange select2.min.js:22 
O.onSelect select2.min.js:22 
O.selectHighlighted select2.min.js:21 
(anonymous function) select2.min.js:21 
O.bind jquery.js:4641 
m.event.dispatch jquery.js:4309

I think the problem is in edit:1265

**Comment by rande** [comment]
So something is wrong in the javascript here: https://github.com/sonata-project/SonataFormatterBundle/blob/master/Resources/views/Form/formatter.html.twig#L31-L33

Can you check in the generated html that all js variables exist ?

**Comment by skillberto** [comment]
Yes, I got a same error. If I use the sandbox configuration, it looks good. But if I use all of jQuery UI component, like *ui.min.js, and minimalized jQuery, than will be the problem. I don't understand the effect of UI library and the original jQuery.min.js Maybe something wrong with the generated js at the html, what did @rande mention abow.

**Comment by jessevanmuijden** [comment]
jQuery('#s54abd34c42f3e_content_contentFormatter').change(function(event) {
                var elms = jQuery('#s54abd34c42f3e_content_rawContent');
                elms.markItUpRemove();
                if (s54abd34c42f3e_rawContent_rich_instance) {
                    s54abd34c42f3e_rawContent_rich_instance.destroy();
                }

                var val = jQuery(this).val();
                var appendClass = val;
                switch(val) {
                    case 'textile':
                        elms.markItUp(markitup_sonataTextileSettings);
                        break;
                    case 'markdown':
                        elms.markItUp(markitup_sonataMarkdownSettings);
                        break;
                    case 'bbcode':
                        elms.markItUp(markitup_sonataBBCodeSettings);
                        break;
                    case 'rawhtml':
                        elms.markItUp(markitup_sonataHtmlSettings);
                        appendClass = 'html';
                        break;
                    case 'richhtml':
                        s54abd34c42f3e_rawContent_rich_instance = CKEDITOR.replace("s54abd34c42f3e_content_rawContent", {"toolbar":[["Bold","Italic","Underline","-","Cut","Copy","Paste","PasteText","PasteFromWord","-","Undo","Redo","-","NumberedList","BulletedList","-","Outdent","Indent","-","Blockquote","-","Image","Link","Unlink","Table"],["Maximize","Source"]]});;

                }

                var parent = elms.parents('div.markItUp');

                if (parent) {
                    for (name in ['textile', 'markdown', 'bbcode', 'rawhtml', 'richhtml', 'rawhtml']) {
                        parent.removeClass(name)
                    }

                    parent.addClass(appendClass);
                }
            });

**Comment by skillberto** [comment]
Yes, this is the code. So as I mentioned, I don't understand why doesn't implemented the "XYZ_rawContent_rich_instance" instance, and I don't understand how can the code goes into the "if (XYZ_rawContent_rich_instance) " case, if the instance doesn't exist...

**Comment by rande** [comment]
I think for a particular reason the js event is registered twice ... can you try to console.log in the twig file to confirm that

**Comment by jessevanmuijden** [comment]
it is only called once. and indeed, as @skillberto points out, the instance is not destroyed at that point. it just does not seem to have the method destroy.

**Comment by jessevanmuijden** [comment]
```
{elementMode: 1, name: "s54abe193492d9_content_rawContent", _: Object, commands: Object, templates: Object…}_: ObjectactiveEnterMode: 1activeShiftEnterMode: 2addMenuGroup: function (b,a){m[b]=a||100}addMenuItem: function (a,c){m[c.group]&&(l[a]=new CKEDITOR.menuItem(this,a,c))}addMenuItems: function (a){for(var c in a)this.addMenuItem(c,a[c])}blockless: falsecommands: Objectconfig: CKEDITOR.tools.prototypedCopy.fcontainer: CKEDITOR.dom.elementcontextMenu: CKEDITOR.plugins.contextMenu.CKEDITOR.tools.createClass.$dataProcessor: CKEDITOR.htmlDataProcessorelementMode: 1enterMode: 1focusManager: CKEDITOR.focusManagergetClipboardData: function (a,d){function c(a){a.removeListener();a.cancel();d(a.data)}function j(a){a.removeListener();a.cancel();i=!0;d({type:f,dataValue:a.data})}function l(){this.customTitle=a&&a.title}var g=!1,f="auto",i=!1;d||(d=a,a=null);b.on("paste",c,null,null,getColorFromDialog: function (c,f){var d=function(a){this.removeListener("ok",d);this.removeListener("cancel",d);a="ok"==a.name?this.getValueOf("picker","selectedColor"):null;c.call(f,a)},e=function(a){a.on("ok",d);a.on("cancel",d)};b.execCommand("colordialog");if(b._.storedDialogs&&getMenuItem: function (a){return l[a]}id: "cke_1"instanceReady: truekeystrokeHandler: CKEDITOR.keystrokeHandlerlang: CKEDITOR.tools.prototypedCopy.flangCode: "en"loaded: truemode: "wysiwyg"name: "s54abe193492d9_content_rawContent"plugins: ObjectreadOnly: falseremoveMenuItem: function (a){delete l[a]}resetUndo: function (){d.reset();a.fire("saveSnapshot")}shiftEnterMode: 2status: "destroyed"tabIndex: 0templates: Objecttitle: "Rich Text Editor, s54abe193492d9_content_rawContent"toolbar: Array[2]toolbox: uui: CKEDITOR.uiundoManager: CKEDITOR.plugins.undo.UndoManager__proto__: CKEDITOR.editor.CKEDITOR.editor
```

**Comment by skillberto** [comment]
And what do you think about my point of other jquery libraries? A bigger (more component) and minimalized libraries can effect to this point? Because if I had changed the original configuration of jquery in sonata sandbox, then appeared the bug (for me).

**Comment by jessevanmuijden** [comment]
i did not clone the sandbox but followed the tutorials

**Comment by skillberto** [comment]
In my case I did not clone it, either. However I used the configuration.

**Comment by wojtekdmyszewicz** [comment]
Fixed it like this:

```javascript
 jQuery(document).ready(function () {

            var fix = fix || {};
            fix.destroyFix = true;
            fix.ckDestroyBugWorkAround = function () {
                if ({{ source_id }}_rich_instance && fix.destroyFix) {
                    {{ source_id }}_rich_instance.destroy();
                }
                fix.destroyFix = false;
            }
```
```javascript
                    case 'text':
                        fix.ckDestroyBugWorkAround();
                        break;
                    case 'markdown':
                        elms.markItUp(markitup_sonataMarkdownSettings);
                        fix.ckDestroyBugWorkAround();
                        break;
                    case 'rawhtml':
                        elms.markItUp(markitup_sonataHtmlSettings);
                        appendClass = 'html';
                        fix.ckDestroyBugWorkAround();
                        break;
                    case 'richhtml':
                        if (!(fix.destroyFix)) {
                            {{ source_id }}_rich_instance = {{ ckeditor_replace(form.children[source_field].vars.id, ckeditor_configuration) }};
                            if ({{ source_id }}_rich_instance) {
                                fix.destroyFix = true;
                            }
                        }
```
```javascript
                if (parent) {
                    for (name in ['text', 'markdown', 'rawhtml', 'richhtml', 'rawhtml', 'html']) {
                        parent.removeClass(name)
                    }

                    parent.addClass(appendClass);
                }
```

**Comment by rande** [comment]
Can you send a PR ? so we can see a diff.

**Comment by wojtekdmyszewicz** [comment]
I will do it asap

**Comment by wojtekdmyszewicz** [comment]
@rande I've send a PR

**Comment by skillberto** [comment]
It will be appear in commit? Or could you please send me too?

**Comment by wojtekdmyszewicz** [comment]
https://github.com/wojtekdmyszewicz/SonataFormatterBundle/commit/732ad74796b4c1fdfee1ae697b5e421c2e2f6fd3

**Comment by skillberto** [comment]
Thank you :)

**Comment by vlepeule** [comment]
Still not working for me with wojtekdmyszewicz@732ad74
Same error...
Any idea ?

**Comment by wojtekdmyszewicz** [comment]
@vlepeule, @rande with the workaround @732ad74 I'm able to switch editor, but after saving the selected editor the destroy error reoccurs.

**Comment by wojtekdmyszewicz** [comment]
@vlepeule, commenting out this line removes the error, but then the state is not properly saved.                    

    jQuery('#{{ form.children[format_field].vars.id }}').trigger('change');

**Comment by picoss** [comment]
Hi,

A possible workaround. To destroy i juste check if the instance name exists in CKEDITOR.instances object. Not sure it's the best way, but it works fine for me.

```javascript
    if ({{ source_id }}_rich_instance && CKEDITOR.instances[{{ source_id }}_rich_instance.name]) {
        CKEDITOR.instances[{{ source_id }}_rich_instance.name].destroy();
    }
```

**Comment by soipo** [comment]
Picoss I tried your  solution and works fine...

**Comment by Arvi89** [comment]
Picoss, Personally I've just modified the "if" statement to make it work, not what's inside.
Would be nice to have an official update :)

**Comment by mcwebb** [comment]
+1 for picoss's solution

**Comment by vovanmix** [comment]
Yes, picoss's solution works

**Comment by oherzeas** [comment]
+1 for picoss's solution

**Comment by tjsmatt** [comment]
Just hit this problem myself, and I think it's because the code's trying to destroy the same CKEditor instance more than once. Suggested fix:

```javascript
if ({{ source_id }}_rich_instance) {
    {{ source_id }}_rich_instance.destroy();
    {{ source_id }}_rich_instance = false; // un-set reference to the now-destroyed editor
}
```

**Comment by skillberto** [comment]
Okay guys, thx. @picoss, would you like to send a PR for this solution? It looks like ~1 year ago..

**Comment by skillberto** [comment]
I found an other issue for this, with PR. #100 fix it with other solution. I close this issue.
