### ISSUE TITLE
Circular reference error when using "sonata.formatter.text.twigengine" in prod mode

### ISSUE THREAD

**Issue by jasperdcbe** [sonata-project/SonataFormatterBundle#90]
When using the "sonata.formatter.text.twigengine" formatter in production mode we receive the following error:

> request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: "Circular reference detected for service "sonata.formatter.pool", path: "sonata.formatter.form.type.selector -> sonata.formatter.pool -> sonata.formatter.text.twigengine -> twig"." at /var/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php line 301 {"exception":"[object](Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException%28code: 0%29: Circular reference detected for service "sonata.formatter.pool", path: "sonata.formatter.form.type.selector -> sonata.formatter.pool -> sonata.formatter.text.twigengine -> twig". at /var/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:301)"} []

Is anyone experiencing the same problem in production? We are using Symfony v2.3.24

**Comment by Th3Mouk** [comment]
@jasperdcbe any news ? Is the issue still relevant ?

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @jasperdcbe
