### ISSUE TITLE
egeloen/ckeditor-bundle & knplabs/knp-markdown-bundle versions need to be updated

### ISSUE THREAD

**Issue by vishalmelmatti** [sonata-project/SonataFormatterBundle#98]
Hi Guys,

egeloen/ckeditor-bundle & knplabs/knp-markdown-bundle bundles are on older versions. Older versions uses framework.templating service which is depricated in symfony 2.7. Is there any plan to update dependencies and make this bundle 2.7 compatible  ?

**Comment by mathieu-axiocode** [comment]
Hi, 

I agree, I need to use the 'input_sync' property of IvoryCKEditorBundle and it is unfortunately not available with the required version in your bundle.

**Comment by Th3Mouk** [comment]
+1 the 'inline' option needed on `egeloen/ckeditor-bundle: ~3.0`

I only use this bundle for the Media / Ckeditor link.

@rande @Soullivaneuh do you think that the logic (routing, controller) between Media and Ckeditor can be extract in the SonataMediaBundle, for people that only use SonataMediaBundle and IvoryCkeditorBundle ?

Cause actually I include the Formatter bundle only for 2/3 actions in a controller.

IMO seem logic but probably you have a different opinion, and probably this only can be merge in 2.4 ? Cause introduce probably BC on 2.3.

Thanks

**Comment by Th3Mouk** [comment]
I've made a PR to upgrade 2.5.x to 3.0.x, but sadly this introduce a BC break for people who have overridden the `formatter.html.twig`

**Comment by Th3Mouk** [comment]
@OskarStark can you close this issue ? thx
